# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Service Course Limited
tagline:             'A home for all your corporate cycling needs'
description:         'A sample use of Prose.io for managing a Jekyll powered site.'
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              ''
  url:               
  email:             

# Custom vars
version:             1.0.0

# Prose vars
prose:
  siteurl: 'http://brynleydavies.github.io/'
  media: 'media'
  ignore:
    - _config.yml
    - /_layouts
    - /_includes
    - /public
    - /.editorconfig
    - /.gitignore
    - /blog.md
    - /atom.xml
    - /LICENSE.md
    - /README.md
    - /404.html

  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
